CREATE TABLE "GCG_4773_PL_Hist"(
 "HIST_NO" BIGINT,
 "RACK" CHAR(15),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "PART" CHAR(20),
 "DESCRIPTION" CHAR(30),
 "QTY_SCANNED" INTEGER,
 "QTY_ORDERED" INTEGER,
 "PROC_TYPE" CHAR(15));

CREATE INDEX "GCG_4773_PL_Hist" ON "GCG_4773_PL_Hist"("HIST_NO", "RACK", "JOB", "SUFFIX");